platform :ios,'9.0'

inhibit_all_warnings!

target 'HighCopyWeChat' do
    pod 'MJExtension', '~> 3.0.13'
    pod 'MJRefresh', '~> 3.1.15.3'
    pod 'SDWebImage', '~> 5.0.0-beta2'
    pod 'Masonry', '~> 1.1.0'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    
end
